### ISSUE TITLE
Unicode attachment file name not being recognized by some mail box.

### ISSUE THREAD

**Issue by vilic** [nodemailer/buildmail#4]
I am experiencing the same issue as https://github.com/andris9/Nodemailer/issues/416, after comparing with mail sources sent from Outlook.com (not via nodemailer), I noticed they use quoted-printable format for attachment file names as well. So I did some modification and it seems to work.

But I don't know whether doing so is safe, any suggestion?

```javascript
//structured = libmime.parseHeaderValue(value);
//if (_self.filename) {
//    structured.params.filename = _self.filename;
//}
//value = libmime.buildHeaderValue(structured);
if (_self.filename) {
    value += '; filename="' + _self._encodeHeaderValue('filename', _self.filename) + '"';
}
```

**Comment by andris9** [comment]
I investigated the issue and it seems that some (mostly web based) e-mail clients still do not support RFC2231 (dates back to 1997) which defines how to use unicode attachment names and only support invalid RFC2047 usage of mime encoded-words. Encoded-words can only be used as atoms and not as quoted strings but you can't use encoded-word without the quotes in parameters because of the = symbols.

Anyway, the solution seems to be to keep the filename in content-disposition as is and add a `name` parameter to content-type with filename in encoded-word encoding. Standards based clients take the RFC2231 encoded filename from content-disposition header and non standard clients take it from the non-standard name property of content-type.

**Comment by vilic** [comment]
I see. Looking forward to an update. :)

**Comment by andris9** [comment]
This was fixed already some time ago

**Comment by vilic** [comment]
:+1:
